version: '3.9'
services:
  app:
    container_name: 'hr_app'
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_ID: ${CUR_USER_ID:-1000}
        GROUP_ID: ${CUR_GROUP_ID:-1000}
        USER_NAME: ${CUR_USER_NAME:-nonroot}
        PHP_VERSION: ${PHP_VERSION:-8.1-fpm}
    image: hr/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      XDEBUG_MODE: '${XDEBUG_MODE:-off}'
    volumes:
      - .:/var/www:delegated
      - /var/www/.env:/var/www/.env:cached
      - /var/www/storage:/var/www/storage:delegated
      - ./docker/php/config/php.ini:/usr/local/etc/php/conf.d/99-local.ini:ro,cached
      - ./docker/php/config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro,cached
      - ./docker/php/config/opcache.ini:/usr/local/etc/php/conf.d/99-opcache.ini:ro,cached
      - ./docker/php/config/zz-www.conf:/usr/local/etc/php-fpm.d/99-zz-www.conf:ro,cached
      - ./docker/supervisor/horizon.conf:/etc/supervisor/conf.d/horizon.conf:ro,cached
      - composer-cache:/home/${CUR_USER_NAME:-nonroot}/.composer,cached
      - /var/log/nginx:/var/log/nginx:ro,cached
      - /var/data/redis:/var/data/redis:ro,cached
    networks:
      - hr
    depends_on:
      - mysql
      - redis
  mysql:
    container_name: 'hr_db'
    image: 'mysql/mysql-server:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - /var/data/mysql:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro,cached
    networks:
      - hr
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
  redis:
    container_name: 'hr_redis'
    image: 'redis/redis-stack-server:latest'
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD}"
    volumes:
      - /var/data/redis:/data
      - ./docker/redis/redis.conf:/redis-stack.conf
    networks:
      - hr
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
  nginx:
    image: nginx:stable-alpine
    container_name: 'hr_nginx'
    restart: unless-stopped
    environment:
      WWWUSER: ${WWWUSER:-nonroot}
    ports:
      - ${FORWARD_HTTP_PORT:-8000}:80
      - ${FORWARD_HTTPS_PORT:-4430}:443
    volumes:
      - ./:/var/www:delegated
      - ./docker/nginx/config/templates:/etc/nginx/templates:ro,cached
      - /var/log/nginx:/var/log/nginx:delegated
      - /var/data/nginx/cache:/var/cache/nginx:delegated
      - /var/files/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt:ro,cached
      - /var/files/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key:ro,cached
      - /var/files/dhparam.pem:/etc/nginx/dhparam.pem:ro,cached
      - ./docker/nginx/config/pma_pass:/etc/nginx/pma_pass:ro
      - ./docker/nginx/config/redis_pass:/etc/nginx/redis_pass:ro
    depends_on:
      - app
      - phpmyadmin
      - redis
    networks:
      - hr

  phpmyadmin:
    container_name: 'hr_pma'
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_ARBITRARY: 1
      PMA_ABSOLUTE_URI: ${APP_URL}/pma/
    links:
      - mysql:mysql
    volumes:
      - ./docker/pma/pma_secure.php:/etc/phpmyadmin/pma_secure.php
    networks:
      - hr
networks:
  hr:
    name: hr_app
volumes:
  composer-cache:
    driver: local
